name: Build/Test

env:
  image_name: ghcr.io/${{ github.repository }}            # Ex: ghcr.io/cseelye/terrain-model

on:
  push:
    branches:
      - '*'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      publish: ${{ steps.setvars.outputs.publish }}
    steps:
      - name: Set variables
        id: setvars
        run: |
          if [[ "${{github.base_ref}}" == "main" || "${{github.ref}}" == "refs/heads/main" ]]; then
              echo "::set-output name=publish::true"
          else
              echo "::set-output name=publish::false"
          fi

  build:
    name: Build/publish container images
    needs:
      - setup
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Github Container Registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Check out repo
        uses: actions/checkout@v2

      - name: Extract metadata for Docker image
        id: meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: |
            ${{ env.image_name }}
          tags: |
            type=raw,value={{date 'YYYYMMDD'}}
          flavor: |
            latest=true

      - name: test
        run: |
          export
          echo "tags = ${{ steps.meta.outputs.tags }}"
          echo "labels = ${{ steps.meta.outputs.labels }}"

      # - name: Build (publish) runtime container
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     target: prod
      #     push: ${{ needs.setup.outputs.publish }}
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
