name: Build/Test

env:
  image_name: ghcr.io/${{ github.repository }}            # Ex: ghcr.io/cseelye/terrain-model
  CORES: 2


on:
  push:
    branches:
      - '*'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      publish: ${{ steps.setvars.outputs.publish }}
    steps:
      - name: Set variables
        id: setvars
        run: |
          if [[ "${{github.base_ref}}" == "main" || "${{github.ref}}" == "refs/heads/main" ]]; then
              echo "::set-output name=publish::true"
          else
              echo "::set-output name=publish::false"
          fi
          echo "::set-output name=date_tag::$(date 'YYYYMMDD')"

  build:
    name: Build/publish container images
    needs:
      - setup
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Github Container Registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set variables
        id: vars
        run: |
          if [[ "${{github.base_ref}}" == "main" || "${{github.ref}}" == "refs/heads/main" ]]; then
              echo "::set-output name=publish::true"
          else
              echo "::set-output name=publish::false"
          fi
          echo "::set-output name=date_tag::$(date 'YYYYMMDD')"

      - name: Build images
        run: |
          make tagged TAG=${{ steps.vars.outputs.date_tag }}
          make tagged TAG=latest

      - name: Push container images
        if: steps.vars.outputs.publish
        run:
          make push TAG=${{ steps.vars.outputs.date_tag }}
          make push TAG=latest
